### ISSUE TITLE
Hw (EEPROM) damage due to vibrations? Or some env variable missing? Basic behaviour changed

### ISSUE THREAD

**Issue by GastonMazzei** [cariboulabs/cariboulite#187]
Hi all, 

Thank you for your time and attention :-) 

I've installed CaribouLite in a Raspberry Pi Zero WH and successfully ran the "capture" python3 example one day ago, with CaribouLite inserted against the Raspberry Pi Zero pins. It went O.K., I haven't paid much attention to this data yet but this is not the point.

Today the union Raspberry Pi Zero + CaribouLite Hat was mounted on a system that vibrates (e.g. a car), in particular vibrations occurred system was powered.

Finally the system was unmounted and the same capture example was ran again, but this time it returns the following. I really hope it's not EEPROM damage due to vibrations, but some missing config that only worked the first time because a lot of e.g. environment variables were correctly set freshly after installation. In any case, how can I check if EEPROM is O.K.? Thanks!

The error message is as follows (triggered during the execution of _sdr = SoapySDR.Device({"driver": "Cariboulite", "channel": "HiF"})_): 

NOTE: this time the antenna plugged to HiF is a 50ohm directional one, i.e. a different one from the ones used the first day.

```
[INFO] SoapyCaribouliteSession, sessionCount: 0
02-13 21:26:33.368  4538  4538 I HAT hat_detect_board@hat.c:619 This board is not configured yet as a hat.
02-13 21:26:33.368  4538  4538 I EEPROM_UTILS eeprom_init_device@eeprom_utils.c:37 i2c-0 has been found successfully
02-13 21:26:33.368  4538  4538 I EEPROM_UTILS eeprom_init_device@eeprom_utils.c:56 trying to modprobe at24
02-13 21:26:33.380  4538  4538 I EEPROM_UTILS eeprom_init_device@eeprom_utils.c:100 EEPROM on addr 0x50 probing successful
02-13 21:26:33.380  4538  4538 E EEPROM_UTILS eeprom_read@eeprom_utils.c:169 The eeprom driver for bus 0, adde 0x50 is not initialized
02-13 21:26:33.380  4538  4538 E HAT hat_init@hat.c:532 Reading from eeprom failed
02-13 21:26:33.380  4538  4538 E CARIBOULITE Setup cariboulite_init_driver_minimal@cariboulite_setup.c:604 Failed to detect the board in /proc/device-tree/hat - EEPROM needs to be configured.
02-13 21:26:33.380  4538  4538 E CARIBOULITE Setup cariboulite_init_driver_minimal@cariboulite_setup.c:605 Please run the cariboulite_prod application with sudo permissions...
[ERROR] cariboulite_init_driver() failed
Printing 'findCariboulite' Request:
    {channel: HiF}
    {driver: Cariboulite}
02-13 21:26:33.383  4538  4538 I HAT hat_detect_board@hat.c:619 This board is not configured yet as a hat.
Traceback (most recent call last):
  File "/home/m4zz31/projects/cariboulite/examples/python/captureB.py", line 121, in <module>
    main()
  File "/home/m4zz31/projects/cariboulite/examples/python/captureB.py", line 77, in main
    sdr = SoapySDR.Device({"driver": "Cariboulite", "channel": "HiF"})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/SoapySDR.py", line 3588, in __new__
    return cls.make(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/SoapySDR.py", line 1806, in make
    return _SoapySDR.Device_make(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: map::at

```

Thanks!

**Comment by GastonMazzei** [comment]
Hi all, apologies for the inconvenience. I'm closing this issue  because the damaged part turns out to be the raspberry device it was  attached to. Thanks.
